### ISSUE TITLE
Transfer pypi ownership to martmists/MCServer

### ISSUE THREAD

**Issue by martmists** [BTaskaya/MCServer#2]
You had no permission to upload this to pypi under your name according to [our license](https://choosealicense.com/no-permission/), so copyright infringement is in play here. We would like to request you to remove the project from pypi and let one of the official developers claim it and/or transfer ownership to me. 

If you refuse, we may choose to take legal actions against you which we can hopefully avoid as it's a waste of time for both of us.

**Comment by BTaskaya** [comment]
Oh, okey. No problem for me, contact me on discord.
